#!/bin/bash

# Define the input file from the previous task
DATA_FILE="data.json"

# Use jq to extract the name, height, weight, and type
# .height and .weight are raw numbers that need to be converted to meters and kilograms
# The type is nested in an array, so we access it with .types[0].type.name
# The values are printed on a single line, separated by spaces
EXTRACTED_DATA=$(jq -r '[.name, .height, .weight, .types[0].type.name] | @tsv' "$DATA_FILE")

# Use awk to format the extracted data into the desired sentence
# The values from jq are available to awk as $1, $2, $3, $4
# We convert the height (decimeters) to meters and weight (hectograms) to kilograms
echo "$EXTRACTED_DATA" | awk '{
    # Convert height from decimeters to meters
    height_m = $2 / 10
    # Convert weight from hectograms to kilograms
    weight_kg = $3 / 10

    printf "%s is of type %s, weighs %skg, and is %.1fm tall.\n", $1, $4, weight_kg, height_m
}'

